PENDING     =1	
PROCESSING  =2	    
READY       =3	
ONHOLD      =4	
CANCELED    =5	    
RECALL      =6	
HIGH        =7	
ASSIGN      =8	
INCOMING    =9	    
CLOSE       =10

class komsOrderStatus:
    PENDING     ='1'	
    PROCESSING  ='2'	    
    READY       ='3'	
    ONHOLD      ='4'	
    CANCELED    ='5'	    
    RECALL      ='6'	
    HIGH        ='7'	
    ASSIGN      ='8'	
    INCOMING    ='9'	    
    CLOSE       ='10'